# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x0craft_service\";\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\"\x81\x01\n\nAppendArgs\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderID\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\'\n\x07\x65ntries\x18\x04 \x03(\x0b\x32\x16.raft_service.LogEntry\x12\x14\n\x0cleaderCommit\x18\x05 \x01(\x05\"[\n\x0bReqVoteArgs\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateID\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"/\n\x0e\x41ppendResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"4\n\x0fReqVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\x32\xa1\x01\n\x0bRaftService\x12H\n\x0e\x61ppend_entries\x12\x18.raft_service.AppendArgs\x1a\x1c.raft_service.AppendResponse\x12H\n\x0crequest_vote\x12\x19.raft_service.ReqVoteArgs\x1a\x1d.raft_service.ReqVoteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGENTRY']._serialized_start=28
  _globals['_LOGENTRY']._serialized_end=87
  _globals['_APPENDARGS']._serialized_start=90
  _globals['_APPENDARGS']._serialized_end=219
  _globals['_REQVOTEARGS']._serialized_start=221
  _globals['_REQVOTEARGS']._serialized_end=312
  _globals['_APPENDRESPONSE']._serialized_start=314
  _globals['_APPENDRESPONSE']._serialized_end=361
  _globals['_REQVOTERESPONSE']._serialized_start=363
  _globals['_REQVOTERESPONSE']._serialized_end=415
  _globals['_RAFTSERVICE']._serialized_start=418
  _globals['_RAFTSERVICE']._serialized_end=579
# @@protoc_insertion_point(module_scope)
